Description: VPC setup for Counterstrike gaming server

# Default parameters can be overridden by command line execution
Parameters:
  AvailabilityZones:
    Description:
      "List of AZs"
    Type: CommaDelimitedList
    Default: eu-west-2a
  VpcCidr:
    Description: "CIDR block for the VPC"
    Type: String
    Default: "172.16.99.0/27" # 32 total addresses should be more than enough
  PubASubnetCidr:
    Description: "CIDR block for our subnet"
    Type: String
    Default: "172.16.99.0/28" # 16 addresses

Resources:
  # Setup vpc
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      InstanceTenancy: default
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-vpc"

  # public subnet AZ-a
  SubnetPubA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !Ref AvailabilityZones]
      CidrBlock: !Ref PubASubnetCidr
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-pub-a"
        - Key: SubnetType
          Value: Public
        - Key: Tier
          Value: Public

  # creates IGW
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-igw"

  # Attaches IGW to vpc
  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-pub-rt"
        - Key: Network
          Value: Public
      VpcId: !Ref VPC

  # Public Route table to InternetGateway in each AZ
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachInternetGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

Outputs:
  VPC:
    Description: VPC ID
    Export:
      Name: !Sub "${AWS::StackName}-vpc"
    Value: !Ref VPC
